CREATE TABLE IF NOT EXISTS books (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  isbn VARCHAR(13),
  price DECIMAL(10,2) NOT NULL,
  condition VARCHAR(50) NOT NULL,
  description TEXT,
  image_url VARCHAR(255),
  seller_id INT NOT NULL,
  status ENUM('AVAILABLE', 'SOLD', 'PENDING') DEFAULT 'AVAILABLE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE
); 