CREATE TABLE IF NOT EXISTS book_updates (
    id INT PRIMARY KEY AUTO_INCREMENT,
    book_id INT NOT NULL,
    update_type ENUM('UPDATE', 'DELETE') NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
); 