CREATE TABLE IF NOT EXISTS history (
    id INT PRIMARY KEY AUTO_INCREMENT,
    bookId INT NOT NULL,
    sellerId INT NOT NULL,
    buyerId INT NOT NULL,
    bookName VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    status ENUM('APPROVED', 'REJECTED') NOT NULL,
    requestDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bookId) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (sellerId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (buyerId) REFERENCES buyers(id) ON DELETE CASCADE
); 